version: '2'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "3000:9000" # http
      - "443:443" # https
    # file with environment declarations for the container
    env_file:
      - docker/web/.env
    # Link to containers in another service
    links:
      - db
    # sync workspace folder with /go
    volumes:
     - ../../../../.:/go
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: pasaribu
      MYSQL_DATABASE: shopee
      MYSQL_IP_ADDR: 127.0.0.1
      MYSQL_PORT: 3306
    # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
    # folder is at workspace root.
    volumes:
      - ../../../../_local_mysql_data:/var/lib/mysql